# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          name: {{ .Values.deployment.name }}
          resources:
{{ toYaml .Values.deployment.resources | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          env:
            - name: ARGOCD_APP_NAME
              value: {{ .Values.env.ARGOCD_APP_NAME }}
            - name: ARGOCD_APP_NAMESPACE
              value: {{ .Values.env.ARGOCD_APP_NAMESPACE }}
            - name: ARGOCD_APP_REVISION
              value: {{ .Values.env.ARGOCD_APP_REVISION }}
            - name: ARGOCD_APP_REVISION_SHORT
              value: {{ .Values.env.ARGOCD_APP_REVISION_SHORT }}
            - name: ARGOCD_APP_SOURCE_PATH
              value: {{ .Values.env.ARGOCD_APP_SOURCE_PATH }}
            - name: ARGOCD_APP_SOURCE_REPO_URL
              value: {{ .Values.env.ARGOCD_APP_SOURCE_REPO_URL }}
            - name: ARGOCD_APP_SOURCE_TARGET_REVISION
              value: {{ .Values.env.ARGOCD_APP_SOURCE_TARGET_REVISION }}
            - name: KUBE_VERSION
              value: {{ .Values.env.KUBE_VERSION }}
            - name: KUBE_API_VERSIONS
              value: {{ .Values.env.KUBE_API_VERSIONS }}
