# values.yaml
deployment:
  name: hello-world
  replicas: 1
  revisionHistoryLimit: 3
  image:
    repository: nginx
    tag: alpine
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  containerPort: 80

service:
  name: hello-world
  port: 80

env:
  ARGOCD_APP_NAME: ''
  ARGOCD_APP_NAMESPACE: ''
  ARGOCD_APP_REVISION: ''
  ARGOCD_APP_REVISION_SHORT: ''
  ARGOCD_APP_SOURCE_PATH: ''
  ARGOCD_APP_SOURCE_REPO_URL: ''
  ARGOCD_APP_SOURCE_TARGET_REVISION: ''
  ARGOCD_APP_LABELS: ''
  ARGOCD_APP_SPEC: ''
