apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jdcmarques/argocd-apps-test'
    path: hello-world
    targetRevision: main
    helm:
      parameters:
        - name: env.ARGOCD_APP_NAME
          value: $ARGOCD_APP_NAME
        - name: env.ARGOCD_APP_NAMESPACE
          value: $ARGOCD_APP_NAMESPACE
        - name: env.ARGOCD_APP_REVISION
          value: $ARGOCD_APP_REVISION
        - name: env.ARGOCD_APP_REVISION_SHORT
          value: $ARGOCD_APP_REVISION_SHORT
        - name: env.ARGOCD_APP_SOURCE_PATH
          value: $ARGOCD_APP_SOURCE_PATH
        - name: env.ARGOCD_APP_SOURCE_REPO_URL
          value: $ARGOCD_APP_SOURCE_REPO_URL
        - name: env.ARGOCD_APP_SOURCE_TARGET_REVISION
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: env.ARGOCD_APP_LABELS
          value: $ARGOCD_APP_LABELS
        - name: env.ARGOCD_APP_SPEC
          value: $ARGOCD_APP_SPEC
  destination:
    namespace: hello-world
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
